kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx8192M -XX:MaxMetaspaceSize=2048M

#Gradle
org.gradle.jvmargs=-Xmx8192M -XX:MaxMetaspaceSize=2048M -Dfile.encoding=UTF-8 -XX:+UseG1GC

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Kotlin Multiplatform
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
kotlin.apple.xcodeCompatibility.nowarn=true

#Kotlin/Native optimizations and stability
kotlin.native.binary.memoryModel=experimental
kotlin.native.cacheKind=none
kotlin.native.binary.freezing=disabled
kotlin.native.binary.objcExportSuspendFunctionLaunchThreadRestriction=none
